# #Clerk Backend API
#
##The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-03-12`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
#
#The version of the OpenAPI document: 2025-03-12
#Contact: support@clerk.com
#Generated by: https://openapi-generator.tech
#Generator version: 7.12.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for Clerk::ClientsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "ClientsApi" do
  describe "test an instance of ClientsApi" do
    it "should create an instance of ClientsApi" do
      api_instance = Clerk::ClientsApi.new
      # TODO expect(api_instance).to be_instance_of(Clerk::ClientsApi)
    end
  end

  # unit tests for get_client
  # Get a client
  # Returns the details of a client.
  # @param client_id Client ID.
  # @param [Hash] opts the optional parameters
  # @return [Client]
  describe "get_client test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for get_client_list
  # List all clients
  # Returns a list of all clients. The clients are returned sorted by creation date, with the newest clients appearing first. Warning: the endpoint is being deprecated and will be removed in future versions.
  # @param [Hash] opts the optional parameters
  # @option opts [Bool] :paginated Whether to paginate the results. If true, the results will be paginated. If false, the results will not be paginated.
  # @option opts [Int32] :limit Applies a limit to the number of results returned. Can be used for paginating the results together with &#x60;offset&#x60;.
  # @option opts [Int32] :offset Skip the first &#x60;offset&#x60; results when paginating. Needs to be an integer greater or equal to zero. To be used in conjunction with &#x60;limit&#x60;.
  # @return [Array(Client)]
  describe "get_client_list test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for verify_client
  # Verify a client
  # Verifies the client in the provided token
  # @param [Hash] opts the optional parameters
  # @option opts [VerifyClientRequest] :verify_client_request Parameters.
  # @return [Client]
  describe "verify_client test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
