# #Clerk Backend API
#
##The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-03-12`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
#
#The version of the OpenAPI document: 2025-03-12
#Contact: support@clerk.com
#Generated by: https://openapi-generator.tech
#Generator version: 7.12.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for Clerk::RedirectURLsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "RedirectURLsApi" do
  describe "test an instance of RedirectURLsApi" do
    it "should create an instance of RedirectURLsApi" do
      api_instance = Clerk::RedirectURLsApi.new
      # TODO expect(api_instance).to be_instance_of(Clerk::RedirectURLsApi)
    end
  end

  # unit tests for create_redirect_url
  # Create a redirect URL
  # Create a redirect URL
  # @param [Hash] opts the optional parameters
  # @option opts [CreateRedirectURLRequest] :create_redirect_url_request 
  # @return [RedirectURL]
  describe "create_redirect_url test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for delete_redirect_url
  # Delete a redirect URL
  # Remove the selected redirect URL from the whitelist of the instance
  # @param id The ID of the redirect URL
  # @param [Hash] opts the optional parameters
  # @return [DeletedObject]
  describe "delete_redirect_url test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for get_redirect_url
  # Retrieve a redirect URL
  # Retrieve the details of the redirect URL with the given ID
  # @param id The ID of the redirect URL
  # @param [Hash] opts the optional parameters
  # @return [RedirectURL]
  describe "get_redirect_url test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for list_redirect_urls
  # List all redirect URLs
  # Lists all whitelisted redirect_urls for the instance
  # @param [Hash] opts the optional parameters
  # @option opts [Bool] :paginated Whether to paginate the results. If true, the results will be paginated. If false, the results will not be paginated.
  # @option opts [Int32] :limit Applies a limit to the number of results returned. Can be used for paginating the results together with &#x60;offset&#x60;.
  # @option opts [Int32] :offset Skip the first &#x60;offset&#x60; results when paginating. Needs to be an integer greater or equal to zero. To be used in conjunction with &#x60;limit&#x60;.
  # @return [Array(RedirectURL)]
  describe "list_redirect_urls test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
