# #Clerk Backend API
#
##The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-03-12`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
#
#The version of the OpenAPI document: 2025-03-12
#Contact: support@clerk.com
#Generated by: https://openapi-generator.tech
#Generator version: 7.12.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for Clerk::RevokeOrganizationInvitationRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Clerk::RevokeOrganizationInvitationRequest do

  describe "test an instance of RevokeOrganizationInvitationRequest" do
    it "should create an instance of RevokeOrganizationInvitationRequest" do
      #instance = Clerk::RevokeOrganizationInvitationRequest.new
      #expect(instance).to be_instance_of(Clerk::RevokeOrganizationInvitationRequest)
    end
  end
  describe "test attribute 'requesting_user_id'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
