# #Clerk Backend API
#
##The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-03-12`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
#
#The version of the OpenAPI document: 2025-03-12
#Contact: support@clerk.com
#Generated by: https://openapi-generator.tech
#Generator version: 7.12.0
#

require "uri"

module Clerk
  class EmailAddressesApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create an email address
    # Create a new email address
    # @return [EmailAddress]
    def create_email_address(create_email_address_request : CreateEmailAddressRequest?)
      data, _status_code, _headers = create_email_address_with_http_info(create_email_address_request)
      data
    end

    # Create an email address
    # Create a new email address
    # @return [Array<(EmailAddress, Integer, Hash)>] EmailAddress data, response status code and response headers
    def create_email_address_with_http_info(create_email_address_request : CreateEmailAddressRequest?)
      if @api_client.config.debugging
        Log.debug {"Calling API: EmailAddressesApi.create_email_address ..."}
      end
      # resource path
      local_var_path = "/email_addresses"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = create_email_address_request.to_json

      # return_type
      return_type = "EmailAddress"

      # auth_names
      auth_names = ["bearerAuth"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"EmailAddressesApi.create_email_address",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: EmailAddressesApi#create_email_address\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return EmailAddress.from_json(data), status_code, headers
    end

    # Delete an email address
    # Delete the email address with the given ID
    # @param email_address_id [String] The ID of the email address to delete
    # @return [DeletedObject]
    def delete_email_address(email_address_id : String)
      data, _status_code, _headers = delete_email_address_with_http_info(email_address_id)
      data
    end

    # Delete an email address
    # Delete the email address with the given ID
    # @param email_address_id [String] The ID of the email address to delete
    # @return [Array<(DeletedObject, Integer, Hash)>] DeletedObject data, response status code and response headers
    def delete_email_address_with_http_info(email_address_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: EmailAddressesApi.delete_email_address ..."}
      end
      # verify the required parameter "email_address_id" is set
      if @api_client.config.client_side_validation && email_address_id.nil?
        raise ArgumentError.new("Missing the required parameter 'email_address_id' when calling EmailAddressesApi.delete_email_address")
      end
      # resource path
      local_var_path = "/email_addresses/{email_address_id}".sub("{" + "email_address_id" + "}", URI.encode_path(email_address_id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "DeletedObject"

      # auth_names
      auth_names = ["bearerAuth"]

      data, status_code, headers = @api_client.call_api(:DELETE,
                                                        local_var_path,
                                                        :"EmailAddressesApi.delete_email_address",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: EmailAddressesApi#delete_email_address\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DeletedObject.from_json(data), status_code, headers
    end

    # Retrieve an email address
    # Returns the details of an email address.
    # @param email_address_id [String] The ID of the email address to retrieve
    # @return [EmailAddress]
    def get_email_address(email_address_id : String)
      data, _status_code, _headers = get_email_address_with_http_info(email_address_id)
      data
    end

    # Retrieve an email address
    # Returns the details of an email address.
    # @param email_address_id [String] The ID of the email address to retrieve
    # @return [Array<(EmailAddress, Integer, Hash)>] EmailAddress data, response status code and response headers
    def get_email_address_with_http_info(email_address_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: EmailAddressesApi.get_email_address ..."}
      end
      # verify the required parameter "email_address_id" is set
      if @api_client.config.client_side_validation && email_address_id.nil?
        raise ArgumentError.new("Missing the required parameter 'email_address_id' when calling EmailAddressesApi.get_email_address")
      end
      # resource path
      local_var_path = "/email_addresses/{email_address_id}".sub("{" + "email_address_id" + "}", URI.encode_path(email_address_id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "EmailAddress"

      # auth_names
      auth_names = ["bearerAuth"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"EmailAddressesApi.get_email_address",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: EmailAddressesApi#get_email_address\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return EmailAddress.from_json(data), status_code, headers
    end

    # Update an email address
    # Updates an email address.
    # @param email_address_id [String] The ID of the email address to update
    # @return [EmailAddress]
    def update_email_address(email_address_id : String, update_email_address_request : UpdateEmailAddressRequest?)
      data, _status_code, _headers = update_email_address_with_http_info(email_address_id, update_email_address_request)
      data
    end

    # Update an email address
    # Updates an email address.
    # @param email_address_id [String] The ID of the email address to update
    # @return [Array<(EmailAddress, Integer, Hash)>] EmailAddress data, response status code and response headers
    def update_email_address_with_http_info(email_address_id : String, update_email_address_request : UpdateEmailAddressRequest?)
      if @api_client.config.debugging
        Log.debug {"Calling API: EmailAddressesApi.update_email_address ..."}
      end
      # verify the required parameter "email_address_id" is set
      if @api_client.config.client_side_validation && email_address_id.nil?
        raise ArgumentError.new("Missing the required parameter 'email_address_id' when calling EmailAddressesApi.update_email_address")
      end
      # resource path
      local_var_path = "/email_addresses/{email_address_id}".sub("{" + "email_address_id" + "}", URI.encode_path(email_address_id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = update_email_address_request.to_json

      # return_type
      return_type = "EmailAddress"

      # auth_names
      auth_names = ["bearerAuth"]

      data, status_code, headers = @api_client.call_api(:PATCH,
                                                        local_var_path,
                                                        :"EmailAddressesApi.update_email_address",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: EmailAddressesApi#update_email_address\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return EmailAddress.from_json(data), status_code, headers
    end
  end
end
