# #Clerk Backend API
#
##The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-03-12`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
#
#The version of the OpenAPI document: 2025-03-12
#Contact: support@clerk.com
#Generated by: https://openapi-generator.tech
#Generator version: 7.12.0
#

require "uri"

module Clerk
  class SignUpsApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Retrieve a sign-up by ID
    # Retrieve the details of the sign-up with the given ID
    # @param id [String] The ID of the sign-up to retrieve
    # @return [SignUp]
    def get_sign_up(id : String)
      data, _status_code, _headers = get_sign_up_with_http_info(id)
      data
    end

    # Retrieve a sign-up by ID
    # Retrieve the details of the sign-up with the given ID
    # @param id [String] The ID of the sign-up to retrieve
    # @return [Array<(SignUp, Integer, Hash)>] SignUp data, response status code and response headers
    def get_sign_up_with_http_info(id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: SignUpsApi.get_sign_up ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling SignUpsApi.get_sign_up")
      end
      # resource path
      local_var_path = "/sign_ups/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "SignUp"

      # auth_names
      auth_names = ["bearerAuth"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"SignUpsApi.get_sign_up",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: SignUpsApi#get_sign_up\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return SignUp.from_json(data), status_code, headers
    end

    # Update a sign-up
    # Update the sign-up with the given ID
    # @param id [String] The ID of the sign-up to update
    # @return [SignUp]
    def update_sign_up(id : String, update_sign_up_request : UpdateSignUpRequest?)
      data, _status_code, _headers = update_sign_up_with_http_info(id, update_sign_up_request)
      data
    end

    # Update a sign-up
    # Update the sign-up with the given ID
    # @param id [String] The ID of the sign-up to update
    # @return [Array<(SignUp, Integer, Hash)>] SignUp data, response status code and response headers
    def update_sign_up_with_http_info(id : String, update_sign_up_request : UpdateSignUpRequest?)
      if @api_client.config.debugging
        Log.debug {"Calling API: SignUpsApi.update_sign_up ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling SignUpsApi.update_sign_up")
      end
      # resource path
      local_var_path = "/sign_ups/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = update_sign_up_request.to_json

      # return_type
      return_type = "SignUp"

      # auth_names
      auth_names = ["bearerAuth"]

      data, status_code, headers = @api_client.call_api(:PATCH,
                                                        local_var_path,
                                                        :"SignUpsApi.update_sign_up",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: SignUpsApi#update_sign_up\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return SignUp.from_json(data), status_code, headers
    end
  end
end
