# #Clerk Backend API
#
##The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-03-12`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
#
#The version of the OpenAPI document: 2025-03-12
#Contact: support@clerk.com
#Generated by: https://openapi-generator.tech
#Generator version: 7.12.0
#

require "uri"

module Clerk
  class WebhooksApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create a Svix app
    # Create a Svix app and associate it with the current instance
    # @return [SvixURL]
    def create_svix_app()
      data, _status_code, _headers = create_svix_app_with_http_info()
      data
    end

    # Create a Svix app
    # Create a Svix app and associate it with the current instance
    # @return [Array<(SvixURL, Integer, Hash)>] SvixURL data, response status code and response headers
    def create_svix_app_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: WebhooksApi.create_svix_app ..."}
      end
      # resource path
      local_var_path = "/webhooks/svix"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "SvixURL"

      # auth_names
      auth_names = ["bearerAuth"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"WebhooksApi.create_svix_app",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: WebhooksApi#create_svix_app\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return SvixURL.from_json(data), status_code, headers
    end

    # Delete a Svix app
    # Delete a Svix app and disassociate it from the current instance
    # @return [nil]
    def delete_svix_app()
      delete_svix_app_with_http_info()
      nil
    end

    # Delete a Svix app
    # Delete a Svix app and disassociate it from the current instance
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def delete_svix_app_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: WebhooksApi.delete_svix_app ..."}
      end
      # resource path
      local_var_path = "/webhooks/svix"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearerAuth"]

      data, status_code, headers = @api_client.call_api(:DELETE,
                                                        local_var_path,
                                                        :"WebhooksApi.delete_svix_app",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: WebhooksApi#delete_svix_app\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Create a Svix Dashboard URL
    # Generate a new url for accessing the Svix's management dashboard for that particular instance
    # @return [SvixURL]
    def generate_svix_auth_url()
      data, _status_code, _headers = generate_svix_auth_url_with_http_info()
      data
    end

    # Create a Svix Dashboard URL
    # Generate a new url for accessing the Svix&#39;s management dashboard for that particular instance
    # @return [Array<(SvixURL, Integer, Hash)>] SvixURL data, response status code and response headers
    def generate_svix_auth_url_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: WebhooksApi.generate_svix_auth_url ..."}
      end
      # resource path
      local_var_path = "/webhooks/svix_url"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "SvixURL"

      # auth_names
      auth_names = ["bearerAuth"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"WebhooksApi.generate_svix_auth_url",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: WebhooksApi#generate_svix_auth_url\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return SvixURL.from_json(data), status_code, headers
    end
  end
end
