# #Clerk Backend API
#
##The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-03-12`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
#
#The version of the OpenAPI document: 2025-03-12
#Contact: support@clerk.com
#Generated by: https://openapi-generator.tech
#Generator version: 7.12.0
#

require "big"
require "json"
require "time"

module Clerk
  class CreateSAMLConnectionRequest
    include JSON::Serializable

    # Required properties
    # The name to use as a label for this SAML Connection
    @[JSON::Field(key: "name", type: String, nillable: false, emit_null: false)]
    property name : String

    # The domain of your organization. Sign in flows using an email with this domain, will use this SAML Connection.
    @[JSON::Field(key: "domain", type: String, nillable: false, emit_null: false)]
    property domain : String

    # The IdP provider of the connection.
    @[JSON::Field(key: "provider", type: String, nillable: false, emit_null: false)]
    property provider : String

    # Optional properties
    # The Entity ID as provided by the IdP
    @[JSON::Field(key: "idp_entity_id", type: String?, nillable: true, emit_null: false)]
    property idp_entity_id : String?

    # The Single-Sign On URL as provided by the IdP
    @[JSON::Field(key: "idp_sso_url", type: String?, nillable: true, emit_null: false)]
    property idp_sso_url : String?

    # The X.509 certificate as provided by the IdP
    @[JSON::Field(key: "idp_certificate", type: String?, nillable: true, emit_null: false)]
    property idp_certificate : String?

    # The URL which serves the IdP metadata. If present, it takes priority over the corresponding individual properties
    @[JSON::Field(key: "idp_metadata_url", type: String?, nillable: true, emit_null: false)]
    property idp_metadata_url : String?

    # The XML content of the IdP metadata file. If present, it takes priority over the corresponding individual properties
    @[JSON::Field(key: "idp_metadata", type: String?, nillable: true, emit_null: false)]
    property idp_metadata : String?

    # The ID of the organization to which users of this SAML Connection will be added
    @[JSON::Field(key: "organization_id", type: String?, nillable: true, emit_null: false)]
    property organization_id : String?

    @[JSON::Field(key: "attribute_mapping", type: CreateSAMLConnectionRequestAttributeMapping?, nillable: true, emit_null: false)]
    property attribute_mapping : CreateSAMLConnectionRequestAttributeMapping?

    class EnumAttributeValidator
      getter datatype : String
      getter allowable_values : Array(String)

      def initialize(datatype, allowable_values)
        @datatype = datatype
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.includes?(value)
      end
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@name : String, @domain : String, @provider : String, @idp_entity_id : String?, @idp_sso_url : String?, @idp_certificate : String?, @idp_metadata_url : String?, @idp_metadata : String?, @organization_id : String?, @attribute_mapping : CreateSAMLConnectionRequestAttributeMapping?)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      provider_validator = EnumAttributeValidator.new("String", ["saml_custom", "saml_okta", "saml_google", "saml_microsoft"])
      return false unless provider_validator.valid?(@provider)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] provider Object to be assigned
    def provider=(provider)
      validator = EnumAttributeValidator.new("String", ["saml_custom", "saml_okta", "saml_google", "saml_microsoft"])
      unless validator.valid?(provider)
        raise ArgumentError.new("invalid value for \"provider\", must be one of #{validator.allowable_values}.")
      end
      @provider = provider
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.same?(o)
      self.class == o.class &&
          name == o.name &&
          domain == o.domain &&
          provider == o.provider &&
          idp_entity_id == o.idp_entity_id &&
          idp_sso_url == o.idp_sso_url &&
          idp_certificate == o.idp_certificate &&
          idp_metadata_url == o.idp_metadata_url &&
          idp_metadata == o.idp_metadata &&
          organization_id == o.organization_id &&
          attribute_mapping == o.attribute_mapping
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, domain, provider, idp_entity_id, idp_sso_url, idp_certificate, idp_metadata_url, idp_metadata, organization_id, attribute_mapping].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if !attributes[self.class.attribute_map[key]]? && self.class.openapi_nullable.includes?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        ({} of Symbol => String).tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Clerk.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {} of Symbol => String
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.includes?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        ({} of Symbol => String).tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
